# LCS Code

Let's see how well the code matches the approach we sketched out...

In [2]:
from numpy import *

def findLCS(v, w):
    score = zeros((len(v)+1,len(w)+1), dtype="int32")
    backt = zeros((len(v)+1,len(w)+1), dtype="int32")
    for i in range(1,len(v)+1):
        for j in range(1,len(w)+1):
            # find best score at each vertex
            if (v[i-1] == w[j-1]):  # test for a match ("diagonal street")
                score[i,j], backt[i,j] = max((score[i-1,j-1]+1,3), (score[i-1,j],1), (score[i,j-1],2))
            else:
                score[i,j], backt[i,j] = max((score[i-1,j],1), (score[i,j-1],2))
    return score, backt

v = "ATGTTAT"
w = "ATCGTAC"
s, b = findLCS(v,w)
for i in range(len(s)):
    print("%10s %-20s    %12s %-20s" % ('' if i else 'score =', str(s[i]), '' if i else 'backtrack =', str(b[i])))

   score = [0 0 0 0 0 0 0 0]        backtrack = [0 0 0 0 0 0 0 0]   
           [0 1 1 1 1 1 1 1]                    [0 3 2 2 2 2 3 2]   
           [0 1 2 2 2 2 2 2]                    [0 1 3 2 2 3 2 2]   
           [0 1 2 2 3 3 3 3]                    [0 1 1 2 3 2 2 2]   
           [0 1 2 2 3 4 4 4]                    [0 1 3 2 1 3 2 2]   
           [0 1 2 2 3 4 4 4]                    [0 1 3 2 1 3 2 2]   
           [0 1 2 2 3 4 5 5]                    [0 3 1 2 1 1 3 2]   
           [0 1 2 2 3 4 5 5]                    [0 1 3 2 1 3 1 2]   


# Code to extract an answer

A simple recursive LCS() routine to return along the path of arrows that led to our best score.

In [3]:
def LCS(b,v,i,j):
    if ((i == 0) and (j == 0)):
        return ''
    elif (b[i,j] == 3):
        return LCS(b,v,i-1,j-1) + v[i-1]
    elif (b[i,j] == 2):
        return LCS(b,v,i,j-1)
    else:
        return LCS(b,v,i-1,j)
        
print(LCS(b,v,b.shape[0]-1,b.shape[1]-1))

ATGTA


# An alignment of v and w

In [4]:
def Alignment(b,v,w,i,j):
    if ((i == 0) and (j == 0)):
        return ['','']
    if (b[i,j] == 3):
        result = Alignment(b,v,w,i-1,j-1)
        result[0] += v[i-1]
        result[1] += w[j-1]
        return result
    if (b[i,j] == 2):
        result = Alignment(b,v,w,i,j-1)
        result[0] += "_"
        result[1] += w[j-1]
        return result
    if (b[i,j] == 1):
        result = Alignment(b,v,w,i-1,j)
        result[0] += v[i-1]
        result[1] += "_"
        return result

align = Alignment(b,v,w,b.shape[0]-1,b.shape[1]-1)
print("v =", align[0])
print("w =", align[1])

v = AT_GTTAT_
w = ATCG_TA_C
